function Pitanja_POT(a){
	var daj;
	switch(a){
		case 1: daj = "Sta je to astigmatizam?";break;
		case 2: daj = "Kako se zove grcka boginja mjeseca?";break;
		case 3: daj = "Koje godine je otkrivena Amerika?";break;
		case 4: daj = "Koliko iznosi sinus od 90 stepeni?";break;
		case 5: daj = "Koje se boja dobija mijesanjem roze i ljubicaste?";break;
		case 6: daj = "Koja je najduza rijeka na svijetu koja protice kroz samo jednu drzavu?";break;
		case 7: daj = "Koje godine je u srbiji uvedeno ljetnje racunanje vremena?";break;
		case 8: daj = "Kako se dzingis-kan zvao na rodjenju?";break;
		case 9: daj = "Pod kojim imenom je izgradio muzicku karijeru holandski di-dzej tajs vervest?";break;
		case 10: daj = "Koji olimpijski sport ima osnovnu podjelu na 3 i 10 metara?";break;
		case 11: daj = "Klepsidra je stara naprava za mjerenje vremena pomocu?";break;
		case 12: daj = "'Majka hrabrost i njena djeca' je drama smjestena u vrijeme kog rata?";break;
		case 13: daj = "Tokom kog rata je vodjena kumanovska bitka?";break;
		case 14: daj = "Kornet je muzicki instrument slican kom instrumentu?";break;
		case 15: daj = "Koji nadimak su dijelili Branislav Milenkovic I Branislav Jerinic?";break;
		case 16: daj = "Sta se nalazi na logou internet pretrazivaca safari?";break;
		case 17: daj = "Kako se zove najveci fudbalski stadion u meksiku?";break;
		case 18: daj = "Ko je od navedenih poznatih licnosti renesanse pogubljen 1600. godine?";break;
		case 19: daj = "Trovanje kojim metalom se strucno zove saturnizam?";break;
		case 20: daj = "Kog po redu francuskog kralja luja istorija pamti kao luja debelog?";break;
		case 21: daj = "Kako se zvao hajducki harambasa kome je vuk karadzic 1804. bio pisar?";break;
		case 22: daj = "Sta je gurd?";break;
		case 23: daj = "Na kom kontinentu je snimljen cuveni dokumentarni film 'ta divna stvorenja'?";break;
		case 24: daj = "Za koji filme je Mira nair dobila zlatnog lava u veneciji?";break;
		case 25: daj = "Sta je po zanimanju bio Franc Jozef Straust?";break;
		case 26: daj = "Ko je naslovna junakinja koju u filmu sofije kopole glumi Kirsten Danst?";break;
		case 27: daj = "Ciju sestru Paulinu je antonio kanova ovjekovjecio skulpturom kao veneru?";break;
		case 28: daj = "Koja je religija najzastupljenija u juznoj koreji?";break;
		case 29: daj = "Na rodjendan kog naucnika se svake godine 10. jula obiljezava dan nauke u srbiji?";break;
		case 30: daj = "Ko je pronasao serum protiv difterije i bio prvi dobitnik nobelove nagrade za medicinu 19001.?";break;
		case 31: daj = "U kakvom su srodstvu bili braca artur i henri miler";break;
		case 32: daj = "Pod kojim umjetnickim imenom nam je poznatija Jolanda Kristina Djiljoti?";break;
		case 33: daj = "Koje od navedenih jevandjelja ne spada u sinopticka jevandjelja?";break;
		case 34: daj = "U kom je gradu na zimskim olimpijskim igrama jugoslavija osvojila 1. medalju?";break;
		case 35: daj = "U kom spanskom gradu se nalazi kompleks 'Grad umjetnosti i nauke'?";break;
		case 36: daj = "Kako se rimskim brojevima pise godina u kojoj se odigrala kosovska bitka?";break;
		case 37: daj = "Ko glumi mocarta u filmu amadeus?";break;
		case 38: daj = "Kako se zove gundulicev ep kome fale 2 pjevanja?";break;
		case 39: daj = "Cemu je slican drevni instrument Aluos";break;
		case 40: daj = "Kako se zove glavna nagrada na filmskom festivalu u Cikagu?";break;
		case 41: daj = "Pomocnik strip junaka Dilana Doga zove se i izgleda kao koji komicar?";break;
		case 42: daj = "Koja kraljevska dinastija je naslijednila tjudore na engleskom tronu?";break;
		case 43: daj = "Misko suvakovic je cuveni teoreticar cega?";break;
		case 44: daj = "Koja zlijezda latinskog naziva timus pocinje da atrofira u pubertetu?";break;
		case 45: daj = "Sting je 'Englez u Nju Jorku' a ko je 'Stranac u moskvi'?";break;
		case 46: daj = "Sta je kroz istoriju oznacavala njemacka rijec riter?";break;
		case 47: daj = "Koji glumac filma 'Goli u sedlu' je i reziser tog filma?";break;
		case 48: daj = "Koja kineska dinastija je poznata po skupocjenim vazama?";break;
		case 49: daj = "Koji hemijski element je nazvan po grckoj reci koja u prevodu znaci nepostojan?";break;
		case 50: daj = "Kako se zove njemacki drzavnik Hercog?";break;
		case 51: daj = "Po grckoj mitologiji koliko je bilo sestara gorgona?";break;
		case 52: daj = "Kako se zove orkestar koji nastupa s pjevacicom biljanom krstic?";break;
		case 53: daj = "Cija je ikona u naslovu pripovjetke laze lazarevica?";break;
		case 54: daj = "Koje je najvece ostrvo na balkanskom poluostrvu?";break;
		case 55: daj = "Koje godine je nastala internet enciklopedija Wikipedia kao podrska podrska Nupediji?";break;
		case 56: daj = "Ag je oznaka za koji hemijski element?";break;
		case 57: daj = "Primula je botanicki naziv za koju biljku?";break;
		case 58: daj = "U kom sportu se proslavio majkl felps?";break;
		case 59: daj = "U kom vijeku se dogodila bitka kod velbuza?";break;
		case 60: daj = "U kom evropskom gradu se nalazi galerija moderne umjetnosti Tejt Modern?";break;
		case 61: daj = "U kom gradu se nalazi manakova kuca izfradjena 1830. kao spomenik kulture s bogatom etnografskom zbirkom?";break;
		case 62: daj = "Zamjenom kog glasa nastali su jekavski,ekavski i ikavski izgovori?";break;
		case 63: daj = "Koji knjizevnik je dobio nin-ovu nagradu za djelo 'Sitnicarnica kod srecne ruke'?";break;
		case 64: daj = "Kako se naziva osnovna jedinica organizacije drustva slobodnih zidara tj. masona?";break;
		case 65: daj = "Ko je napisao cuvenu dramu 'Hamlet'?";break;
		case 66: daj = "Ko je napisao djelo 'Bozanstvena komedija'?";break;
		case 67: daj = "Koje je godine komponovano djelo 'Kaljinka'?";break;
		case 68: daj = "Cuveno djelo Leonarda da Vincija je:?";break;
		case 69: daj = "Najpoznatije djelo Boticelija je:";break;
		case 70: daj = "Sliku 'Stvaranje Adama' naslikao je:";break;
		default: break;
	}
	return daj.toUpperCase();
}
function Tacni_Odgovori_POT(a){
	var daj;
	switch(a){
		case 1: daj = "bolest ociju";break;
		case 2: daj = "selena";break;
		case 3: daj = "1492";break;
		case 4: daj = "1";break;
		case 5: daj = "grimizna";break;
		case 6: daj = "jangce";break;
		case 7: daj = "1983";break;
		case 8: daj = "temudzin";break;
		case 9: daj = "tijesto";break;
		case 10: daj = "skokovi u vodu";break;
		case 11: daj = "vode";break;
		case 12: daj = "tridesetogodisnjeg";break;
		case 13: daj = "1. balkanskog";break;
		case 14: daj = "trubi";break;
		case 15: daj = "ciga";break;
		case 16: daj = "kompas";break;
		case 17: daj = "asteka";break;
		case 18: daj = "djordano bruno";break;
		case 19: daj = "olovom";break;
		case 20: daj = "luja 6.";break;
		case 21: daj = "djordje curcija";break;
		case 22: daj = "valuta hatija";break;
		case 23: daj = "Afrika";break;
		case 24: daj = "monsunska svadba";break;
		case 25: daj = "politicar";break;
		case 26: daj = "marija antoaneta";break;
		case 27: daj = "napoleona";break;
		case 28: daj = "hriscanstvo";break;
		case 29: daj = "Nikole tesle";break;
		case 30: daj = "Emil fon bering";break;
		case 31: daj = "ni u kakvom";break;
		case 32: daj = "dalida";break;
		case 33: daj = "po jovanu";break;
		case 34: daj = "sarajevo";break;
		case 35: daj = "valensiji";break;
		case 36: daj = "mccclxxxix";break;
		case 37: daj = "tom hals";break;
		case 38: daj = "osman";break;
		case 39: daj = "oboi";break;
		case 40: daj = "zlatni hugo";break;
		case 41: daj = "Gruco marks";break;
		case 42: daj = "stjuart";break;
		case 43: daj = "umjetnosti";break;
		case 44: daj = "grudna";break;
		case 45: daj = "majkl dzekson";break;
		case 46: daj = "viteza";break;
		case 47: daj = "denis hoper";break;
		case 48: daj = "ming";break;
		case 49: daj = "astat";break;
		case 50: daj = "roman";break;
		case 51: daj = "3";break;
		case 52: daj = "bistrik";break;
		case 53: daj = "skolska";break;
		case 54: daj = "skadarsko";break;
		case 55: daj = "2001";break;
		case 56: daj = "srebro";break;
		case 57: daj = "jagorcevinu";break;
		case 58: daj = "plivanje";break;
		case 59: daj = "14.";break;
		case 60: daj = "london";break;
		case 61: daj = "beograd";break;
		case 62: daj = "jat";break;
		case 63: daj = "GOran petrovic";break;
		case 64: daj = "loza";break;
		case 65: daj = "Viljem Sekspir";break;
		case 66: daj = "Dante Aligijeri";break;
		case 67: daj = "1860";break;
		case 68: daj = "Tajna Vecera";break;
		case 69: daj = "Radjanje Venere";break;
		case 70: daj = "Mikelandjelo Bunaroti";break;
		default: break;
	}
	return daj.toUpperCase();
}
function Pogresni_Odgovori_POT(a){
	switch(a){
		case 1: odgovori_pot[0] = "bolest misica";odgovori_pot[1] = "bolest kostiju";break;
		case 2: odgovori_pot[0] = "demetra";odgovori_pot[1] = "afrodita";break;
		case 3: odgovori_pot[0] = "1942";odgovori_pot[1] = "1493";break;
		case 4: odgovori_pot[0] = "-1";odgovori_pot[1] = "0";break;
		case 5: odgovori_pot[0] = "smedja";odgovori_pot[1] = "tirkizna";break;
		case 6: odgovori_pot[0] = "ind";odgovori_pot[1] = "jenisej";break;
		case 7: odgovori_pot[0] = "1978";odgovori_pot[1] = "1998";break;
		case 8: odgovori_pot[0] = "tamerlan";odgovori_pot[1] = "teturlijan";break;
		case 9: odgovori_pot[0] = "avici";odgovori_pot[1] = "beni benasi";break;
		case 10: odgovori_pot[0] = "strelicarstvo";odgovori_pot[1] = "streljastvo";break;
		case 11: odgovori_pot[0] = "vatre";odgovori_pot[1] = "pijeska";break;
		case 12: odgovori_pot[0] = "sedmogodisnjeg";odgovori_pot[1] = "stogodisnjeg";break;
		case 13: odgovori_pot[0] = "1. svjetskog";odgovori_pot[1] = "2. balkanskog";break;
		case 14: odgovori_pot[0] = "klaviru";odgovori_pot[1] = "violini";break;
		case 15: odgovori_pot[0] = "zika";odgovori_pot[1] = "bata";break;
		case 16: odgovori_pot[0] = "baobab";odgovori_pot[1] = "slon";break;
		case 17: odgovori_pot[0] = "olmeka";odgovori_pot[1] = "tolteka";break;
		case 18: odgovori_pot[0] = "nikola kopernik";odgovori_pot[1] = "dante aligijeri";break;
		case 19: odgovori_pot[0] = "bakrom";odgovori_pot[1] = "zivom";break;
		case 20: odgovori_pot[0] = "luja 7.";odgovori_pot[1] = "luja 9.";break;
		case 21: odgovori_pot[0] = "milenko stojkovic";odgovori_pot[1] = "petar dobrnjac";break;
		case 22: odgovori_pot[0] = "himalajska ovca";odgovori_pot[1] = "figura u klizanju";break;
		case 23: odgovori_pot[0] = "azija";odgovori_pot[1] = "juzna amerika";break;
		case 24: odgovori_pot[0] = "kapernaum";odgovori_pot[1] = "salem bombaj";break;
		case 25: odgovori_pot[0] = "kompozitor";odgovori_pot[1] = "pilot";break;
		case 26: odgovori_pot[0] = "lukrecija bordzija";odgovori_pot[1] = "jovanka orleanka";break;
		case 27: odgovori_pot[0] = "fridriha velikog";odgovori_pot[1] = "petra velikog";break;
		case 28: odgovori_pot[0] = "hintizam";odgovori_pot[1] = "budizam";break;
		case 29: odgovori_pot[0] = "mihajla pupina";odgovori_pot[1] = "milutina milankovica";break;
		case 30: odgovori_pot[0] = "semil vaksman";odgovori_pot[1] = "dzonas edvard salk";break;
		case 31: odgovori_pot[0] = "otac i sin";odgovori_pot[1] = "braca";break;
		case 32: odgovori_pot[0] = "zaz";odgovori_pot[1] = "maria vanesa";break;
		case 33: odgovori_pot[0] = "po luki";odgovori_pot[1] = "po mateju";break;
		case 34: odgovori_pot[0] = "lejk plesid";odgovori_pot[1] = "kalagari";break;
		case 35: odgovori_pot[0] = "barseloni";odgovori_pot[1] = "sevilja";break;
		case 36: odgovori_pot[0] = "mdclxxix";odgovori_pot[1] = "mcdxcix";break;
		case 37: odgovori_pot[0] = "tom henks";odgovori_pot[1] = "tom hardi";break;
		case 38: odgovori_pot[0] = "orhan";odgovori_pot[1] = "obren";break;
		case 39: odgovori_pot[0] = "gitari";odgovori_pot[1] = "harfi";break;
		case 40: odgovori_pot[0] = "zlatni hose";odgovori_pot[1] = "zlatni huan?";break;
		case 41: odgovori_pot[0] = "dzeri luis";odgovori_pot[1] = "beni hil";break;
		case 42: odgovori_pot[0] = "jork";odgovori_pot[1] = "lankaster";break;
		case 43: odgovori_pot[0] = "knjizevnosti";odgovori_pot[1] = "zavjere";break;
		case 44: odgovori_pot[0] = "stitna";odgovori_pot[1] = "nadbubrezna";break;
		case 45: odgovori_pot[0] = "brus springstin";odgovori_pot[1] = "dejvid bouvi";break;
		case 46: odgovori_pot[0] = "svestenika";odgovori_pot[1] = "jeretika";break;
		case 47: odgovori_pot[0] = "dzek niklson";odgovori_pot[1] = "piter fonda";break;
		case 48: odgovori_pot[0] = "tang";odgovori_pot[1] = "kang";break;
		case 49: odgovori_pot[0] = "aktinijum";odgovori_pot[1] = "aluminijum";break;
		case 50: odgovori_pot[0] = "adolf";odgovori_pot[1] = "herbert";break;
		case 51: odgovori_pot[0] = "5";odgovori_pot[1] = "7";break;
		case 52: odgovori_pot[0] = "moje 3";odgovori_pot[1] = "kramer";break;
		case 53: odgovori_pot[0] = "majcina";odgovori_pot[1] = "djecija";break;
		case 54: odgovori_pot[0] = "balton";odgovori_pot[1] = "prepansko";break;
		case 55: odgovori_pot[0] = "2002";odgovori_pot[1] = "2003";break;
		case 56: odgovori_pot[0] = "zlato";odgovori_pot[1] = "bakar";break;
		case 57: odgovori_pot[0] = "narcis";odgovori_pot[1] = "lavandu";break;
		case 58: odgovori_pot[0] = "fudbal";odgovori_pot[1] = "atletika";break;
		case 59: odgovori_pot[0] = "15.";odgovori_pot[1] = "16.";break;
		case 60: odgovori_pot[0] = "Paris";odgovori_pot[1] = "bec";break;
		case 61: odgovori_pot[0] = "sombor";odgovori_pot[1] = "subotica";break;
		case 62: odgovori_pot[0] = "Vanja bulic";odgovori_pot[1] = "Tanja savic";break;
		case 63: odgovori_pot[0] = "trivija";odgovori_pot[1] = "majori";break;
		case 64: odgovori_pot[0] = "kat";odgovori_pot[1] = "pat";break;
		case 65: odgovori_pot[0] = "Francesko Petrarka";odgovori_pot[1] = "Dante Aligijeri";break;
		case 66: odgovori_pot[0] = "Viljem Sekspir";odgovori_pot[1] = "Francesko Petrarka";break;
		case 67: odgovori_pot[0] = "1861";odgovori_pot[1] = "1760";break;
		case 68: odgovori_pot[0] = "David";odgovori_pot[1] = "Vrisak";break;
		case 69: odgovori_pot[0] = "Vrisak";odgovori_pot[1] = "Radjanje Sunca";break;
		case 70: odgovori_pot[0] = "Francesko Petrarka";odgovori_pot[1] = "Rafaelo Santi";break;
		default: break;
	}
	odgovori_pot[0] = odgovori_pot[0].toUpperCase();
	odgovori_pot[1] = odgovori_pot[1].toUpperCase();
}